name: Build Unity project to Windows, MacOS, and Linux

# Runs this workflow on pushes to the main branch and on pull requests to any branch.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS Universal version
          - StandaloneWindows # Build a Windows 32-bit version
          - StandaloneWindows64 # Build a Windows 64-bit version
          - StandaloneLinux64 # Build a Linux 64-bit version
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
          buildName: Bibbity Bobbity Boo
      - uses: actions/upload-artifact@v4
        with:
          name: BibbityBobbityBoo-${{ matrix.targetPlatform }}-${{ steps.builder.outputs.buildVersion }}
          path: build/${{ matrix.targetPlatform }}
